#!/usr/bin/python3.8

# Copyright 2024 Lawrence Livermore National Security, LLC and other
# DFTF Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: BSD-3-Clause

from collections import defaultdict
import hostlist
import itertools
import logging
import multiprocessing
import redfish
import redfish_utilities
import signal
import subprocess
import sys
import time
import yaml

signal_caught = None
logger = None

class Config:
    refresh_interval = 3600
    context_prefix = ''
    purge_unrecognized = False
    max_workers = 400
    log_level = 'warning'

def interrupt_handler(signum, frame):
    global signal_caught
    # We'll ignore overlapping signals
    if signal_caught is None:
        signal_caught = signum
signal.signal(signal.SIGHUP, interrupt_handler)
signal.signal(signal.SIGUSR1, interrupt_handler)
signal.signal(signal.SIGUSR2, interrupt_handler)

def getent_hosts(hostname_or_ip):
    hosts = None
    try:
        hosts = subprocess.run(['getent', 'hosts', hostname_or_ip], stdout=subprocess.PIPE)
        hosts = hosts.stdout.decode("utf-8").split()
    except:
        # FIXME, fake_ip_ line only for testing
        #raise
        return ['FIXME_'+hostname_or_ip]
    return hosts

def set_log_level():
    numeric_level = getattr(logging, Config.log_level.upper(), None)
    if not isinstance(numeric_level, int):
        raise ValueError(f'Invalid log level: {Config.log_level}')
    logger.setLevel(numeric_level)

def parse_config(cf):
    subs = defaultdict(list)

    config = yaml.safe_load(cf)
    try:
        Config.log_level = config['log_level']
    except:
        pass
    else:
        set_log_level()
    try:
        Config.refresh_interval = config['refresh_interval']
    except:
        pass
    try:
        Config.context_prefix = config['context_prefix']
    except:
        pass
    try:
        Config.purge_unrecognized = config['purge_unrecognized']
    except:
        pass
    try:
        Config.max_workers = config['max_workers']
    except:
        pass
    try:
        Config.redfish_username = config['redfish_username']
    except:
        raise Exception(f'Missing "redfish_username" field')
    try:
        Config.redfish_password = config['redfish_password']
    except:
        raise Exception(f'Missing "redfish_password" field')

    for subscription in config['subscriptions']:
        try:
            val = subscription['servers']
        except:
            try:
                val = config['servers']
            except:
                raise Exception(f'Missing "servers" field')
        # 'servers' can be a string or list of strings
        # each string may be a hostlist
        if not isinstance(val, list):
            val = [val]
        servers = []
        for v in val:
            servers.extend(hostlist.string_to_list(v))

        try:
            destinations = subscription['destinations']
        except:
            try:
                destinations = config['destinations']
            except:
                raise Exception(f'Missing "destinations" field')
        try:
            destinations_port = subscription['destinations_port']
        except:
            try:
                destinations_port = config['destinations_port']
            except:
                raise Exception(f'Missing "destinations_port" field')
        try:
            destinations_use_ip = subscription['destinations_use_ip']
        except:
            try:
                destinations_use_ip = config['destinations_use_ip']
            except:
                destinations_use_ip = False


        destinations = hostlist.string_to_list(destinations)
        if destinations_use_ip:
            destinations = [getent_hosts(d)[0] for d in destinations]

        for server, destination in zip(servers, itertools.cycle(destinations)):
            try:
                sub = dict(subscription['properties'])
            except:
                sub = dict()
            sub['Destination'] = destination+':'+str(config['destinations_port'])
            if 'Context' not in sub:
                try:
                    sub['Context'] = Config.context_prefix + subscription['context']
                except:
                    raise Exception(f'missing "context" or "Context" in config')
            if 'Protocol' not in sub:
                sub['Protocol'] = 'Redfish'
            subs[server].append(sub)

    return subs

def read_config_file(config_file):
    subs_map = None
    try:
        with open(config_file, 'r') as cf:
            subs_map = parse_config(cf)
    except Exception as inst:
        logger.error(f'Unable to read config file {config_file}, {inst}')
    return subs_map

def field_match(field, requested, existing):
    if field in requested and field in existing:
        # if they are lists, sort them so we can test equivalence
        if isinstance(existing[field], list):
            existing[field] = sorted(existing[field])
        if isinstance(requested[field], list):
            requested[field] = sorted(requested[field])

        if existing[field] == requested[field]:
            return True
        else:
            return False
    elif field not in requested and field not in existing:
        # field not in either
        return True
    elif field not in requested:
        # an empty list is considered equivalent to no entry
        if isinstance(existing[field], list) and len(existing[field]) == 0:
            return True
        else:
            return False
    elif field not in existing:
        # an empty list is considered equivalent to no entry
        if isinstance(requested[field], list) and len(requested[field]) == 0:
            return True
        else:
            return False
    else:
        # should never get here.
        return True

def partial_match(requested, existing):
    if field_match('Context', requested, existing):
        return True
    return False

known_subscription_properties = [
    'Context',
    'Destination',
    'RegistryPrefixes',
    'ExcludeRegistryPrefixes',
    'MessageIds',
    'ExcludeMessageIds',
    'Protocol'
]

def full_match(requested, existing):
    for prop in known_subscription_properties:
        if not field_match(prop, requested, existing):
            return False
    return True

def compare_subscriptions(requested_subs, existing_subs):
    keep = []
    remove = []
    add = []
    for requested in requested_subs:
        found = False
        for existing in existing_subs:
            if partial_match(requested, existing):
                found = True
                if full_match(requested, existing):
                    keep.append(existing)
                else:
                    remove.append(existing)
                    add.append(requested)
                existing_subs.remove(existing)
                break
        if not found:
            add.append(requested)
    for sub in existing_subs:
        if (Config.context_prefix and sub['Context'][:len(Config.context_prefix)] == Config.context_prefix) \
           or Config.purge_unrecognized:
            remove.append(sub)
        else:
            keep.append(sub)

    return keep, remove, add

def remove_subscription(session, sub):
    session.delete(sub['@odata.id'])

def create_subscription(session, sub):
    event_service = redfish_utilities.get_event_service(session)
    if "Subscriptions" not in event_service:
        raise Exception("Service does not contain a subsciption collection")
    result = session.post(event_service["Subscriptions"]["@odata.id"],
                          body = sub)

# If subs is None or an emptry list, we will only potentially
# remove subscriptions.
def update_one_server(server, subs=None):
    if subs is None:
        subs = []
    try:
        session = redfish.redfish_client(base_url="https://"+server,
                                         username=Config.redfish_username,
                                         password=Config.redfish_password,
                                         default_prefix="/redfish/v1",
                                         timeout=10,
                                         max_retry=1)
        session.login(auth="session")
    except:
        logger.debug(f'failed to connect to redfish server "{server}"')
        return
    try:
        existing = redfish_utilities.get_event_subscriptions(session)
    except:
        logger.debug(f'failed to get subscription list from redfish server "{server}"')
        try:
            session.logout()
        except:
            pass
        return

    try:
        keep, remove, add = compare_subscriptions(subs, existing)
    except Exception as inst:
        logger.warning(f'Unexpected exception during compare_subscriptions for server {server}, {inst}')

    for sub in keep:
        logger.debug(f'Server {server}, keeping sub Context={sub["Context"]}, Destination={sub["Destination"]}')
    for sub in remove:
        logger.debug(f'Server {server}, removing sub Context={sub["Context"]}, Destination={sub["Destination"]}')
        try:
            remove_subscription(session, sub)
        except:
            logger.warning(f'Unable to remove subscription {sub} from redfish server "{server}"')
    for sub in add:
        logger.debug(f'Server {server}, adding sub Context={sub["Context"]}, Destination={sub["Destination"]}')
        try:
            create_subscription(session, sub)
        except:
            logger.warning(f'Unable to create subscription {sub} on redfish server "{server}"')

    try:
        session.logout()
    except:
        logger.debug(f'Session logout failed from redfish server "{server}"')

def update_all_servers(subs_map):
    logger.info('Subscription update cycle beginning')
    num_pool_processes = min(Config.max_workers, len(subs_map))
    with multiprocessing.Pool(num_pool_processes) as pool:
        result = pool.starmap(update_one_server, subs_map.items())
    logger.info('Subscription update cycle finished')

def purge_all_servers(subs_map):
    logger.warning('Subscription purge cycle beginning')
    num_pool_processes = min(Config.max_workers, len(subs_map))
    with multiprocessing.Pool(num_pool_processes) as pool:
        result = pool.map(update_one_server, subs_map.keys())
    logger.warning('Subscription purge cycle finished')

def main():
    global signal_caught
    global logger

    logger = multiprocessing.log_to_stderr()
    set_log_level()

    subs_map = read_config_file(sys.argv[1])

    last_update = 0
    while True:
        time.sleep(0.2)
        if signal_caught is not None:
            sig = signal_caught
            signal_caught = None # reset to allow the next signal
            if sig == signal.SIGHUP \
               or sig == signal.SIGUSR1:
                last_update = time.time()
                logger.info(f'Got signal {sig}')
                subs_map = read_config_file(sys.argv[1])
                update_all_servers(subs_map)
            elif sig == signal.SIGUSR2:
                logger.info(f'Got signal {sig}')
                purge_all_servers(subs_map)
                sys.exit(0)
            else:
                raise Exception(f'unexpected signal {sig}')
        else:
            now = time.time()
            if (now - last_update) > Config.refresh_interval:
                last_update = now
                update_all_servers(subs_map)
            pass

if __name__ == '__main__':
    main()
